name: '🐞 Bug Report'
description: Report unexpected behavior or broken functionality.
title: '[Bug]: '
labels: ['bug']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please describe the problem clearly so it can be reproduced and fixed.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
      placeholder: 'E.g., App crashes when saving a draft'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide clear steps so others can reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: 'The draft should save without errors.'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: 'The app shows an error message and reloads.'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System details (browser, OS, app version, etc.).
      placeholder: 'OS: macOS 14.5, Browser: Chrome 124, App version: 1.2.3'
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or logs.
    validations:
      required: false
